blank_issues_enabled: false
contact_links:
  - name: 💬 微信交流群
    url: https://100.agitao.net/
    about: 加入微信交流群，与其他用户和开发者交流
  - name: 📺 观看演示视频
    url: https://youtu.be/z_rfNVBBLWo
    about: 查看 Tab Hive 的完整功能演示
  - name: 📖 查看文档
    url: https://github.com/MaskerPRC/tab-hive/blob/master/README.md
    about: 阅读完整的使用文档和功能说明

